---
  - name: "Playbook to create users"
    hosts: localhost 

    tasks:
      - name: "Creating users"
        user:
          name: "power"
          home: "/home/power"
          shell: "/bin/bash"
          state: absent
          remove: yes
