---
  - name: "Playbook to create users"
    hosts: localhost 

    tasks:
      - name: "Create a directory"
        file:
          path: "/opt/tomcat"
          state: "directory"
          mode: "0755"
          owner: "smunoz"
          group: "smunoz"

      - name: "Download Tomcat using get_url"
        get_url:
          url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.87/bin/apache-tomcat-9.0.87.zip"
          dest: "/opt/tomcat"
          mode: "0755"
          group: "smunoz"
          owner: "smunoz"
