---
  - name: "Installing and running Apache"
    hosts: nodes
    become: true

    tasks: 
    - name: "Install Apache"
      apt: name=apache2 update_cache=yes state=latest

    - name: "Start Apache"
      service:
        name: apache2
        state: restarted
