Vagrant.configure("2") do |config|
  # Box base ligera (Ubuntu)
  config.vm.box = "bento/almalinux-10"

  # Red privada (acceso desde tu host)
  config.vm.network "private_network", ip: "192.168.56.11"; 

  # Recursos mínimos (ligero)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end
end
